### ISSUE TITLE
curator  use  this.client.create().creatingParentsIfNeeded().withMode(CreateMode.PERSISTENT).forPath(path, data); but I find zk didnot have this node.

### ISSUE THREAD

**Issue by RebornHuan** [Netflix/curator#294]
/workers/10.24.76.52  : writeData
/workers/10.24.76.52  : node not exit
/workers/10.24.76.52  : creatingParentsIfNeeded
/workers/10.24.76.52/state  : writeData
/workers/10.24.76.52/state  : node not exit
2015-03-31 10:02:04,734 ERROR [main] zookeeper.ZookeeperService (ZookeeperService.java:startWorker(342)) - Worker Register Error Happen, Maker Sure Zookeeper Server Can Be Connected
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /workers/10.24.76.52/state
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:688)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:672)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:668)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:453)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:443)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
	at com.suning.cybertron.superion.worker.containermanager.zookeeper.ZookeeperClient.writeData(ZookeeperClient.java:124)
	at com.suning.cybertron.superion.worker.containermanager.zookeeper.ZookeeperClient.makeDir(ZookeeperClient.java:155)
	at com.suning.cybertron.superion.worker.containermanager.zookeeper.ZookeeperService.startWorker(ZookeeperService.java:326)
	at com.suning.cybertron.superion.worker.containermanager.zookeeper.ZookeeperService.serviceStart(Zookeep

**Comment by RebornHuan** [comment]
￼[zk: localhost:2181(CONNECTED) 47] ls /workers
[10.27.89.16, 10.27.89.14, 10.27.89.13, 192.168.146.129, 10.22.28.198, 192.168.126.1]

**Comment by Randgalt** [comment]
Please open issues on the Apache Jira website: https://issues.apache.org/jira/browse/CURATOR
