### ISSUE TITLE
NoSuchMethodError exception

### ISSUE THREAD

**Issue by oikomi** [Netflix/curator#297]
zookeeper version 3.4.6

code

``` java
    public static void main(String[] args) {
        CuratorFramework client = CuratorFrameworkFactory.builder()
                .connectString("localhost:2181")
                .sessionTimeoutMs(5000)
                .connectionTimeoutMs(3000)
                .retryPolicy(new ExponentialBackoffRetry(1000, 3))
                .build();

        client.start();
    }
```

exception:

``` shell
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.zookeeper.server.quorum.flexible.QuorumMaj.<init>(Ljava/util/Map;)V
    at org.apache.curator.framework.imps.EnsembleTracker.<init>(EnsembleTracker.java:54)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.<init>(CuratorFrameworkImpl.java:156)
    at org.apache.curator.framework.CuratorFrameworkFactory$Builder.build(CuratorFrameworkFactory.java:136)
    at org.miaohong.jbfs.store.server.controller.Test.main(Test.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by Randgalt** [comment]
Curator has moved to Apache. Please see: http://curator.apache.org - on that site you can email the Curator mailing lists, add issues to Curator's Jira, etc. For this particular issue, you're probably using Curator 3.0 which requires ZK 3.5.x. Use Curator 2.9.x instead.

**Comment by oikomi** [comment]
@Randgalt thank you
