### ISSUE TITLE
ConnectionLossException using TestingCluster on Java 7 for Mac (Lion)

### ISSUE THREAD

**Issue by slindner** [Netflix/curator#47]
We ran into this problem in our own application tests but I was able to write a Curator-specific test that exhibits the same problem (see below).  This seems to fail over 90% of the time but I have seen it pass randomly.   If I fall back to Java 6 this passes consistently, though our application-level tests still exhibit some flakiness but not in the same exact / reliable manner so we're not sure if this is related.

Here is the stack trace:

2012-03-14 12:54:31,908 ERROR [main] [com.netflix.curator.framework.imps.CuratorFrameworkImpl] Ensure path threw exception
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /namespace
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
    at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1003)
    at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1031)
    at com.netflix.curator.utils.ZKPaths.mkdirs(ZKPaths.java:163)
    at com.netflix.curator.utils.EnsurePath$InitialHelper.ensure(EnsurePath.java:101)
    at com.netflix.curator.utils.EnsurePath.ensure(EnsurePath.java:88)
    at com.netflix.curator.framework.imps.CuratorFrameworkImpl.ensurePath(CuratorFrameworkImpl.java:479)
    at com.netflix.curator.framework.imps.CuratorFrameworkImpl.fixForNamespace(CuratorFrameworkImpl.java:461)
    at com.netflix.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:285)
    at com.netflix.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:279)
    at com.netflix.curator.framework.imps.CreateBuilderImpl$3.forPath(CreateBuilderImpl.java:207)
    at com.netflix.curator.framework.imps.CreateBuilderImpl$3.forPath(CreateBuilderImpl.java:165)

Here is the test code:

////// start test code ////

import java.io.IOException;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.netflix.curator.framework.CuratorFramework;
import com.netflix.curator.framework.CuratorFrameworkFactory;
import com.netflix.curator.retry.ExponentialBackoffRetry;
import com.netflix.curator.test.TestingCluster;

public class CuratorFixtureTest {
    private static final String NAMESPACE = "namespace";

```
TestingCluster testingCluster;

@Before
public void before() throws Exception {
    testingCluster = new TestingCluster(3);
    testingCluster.start();
}

@After
public void after() throws IOException {
    testingCluster.close();

}

@Test
public void foo() throws Exception {
    CuratorFramework framework = CuratorFrameworkFactory.builder().connectString(testingCluster.getConnectString())
            .namespace(NAMESPACE).retryPolicy(new ExponentialBackoffRetry(1, 10)).build();
    try {
        framework.start();

        framework.create().creatingParentsIfNeeded().forPath("/foo22/bar");
    } finally {
        framework.close();
    }

}
```

}

////// end test code ////

**Comment by jackoll8868** [comment]
Hey,guys. I got the same error on MAC OS 10.12.3 JDK8
